name: Demo workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:    
  hello:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - name: demo workflow
         run: echo 'Hello world'
         shell: bash
    
  goodbye:
    runs-on: ubuntu-latest
    steps: 
    - name: goodbye demo workflow
      run: echo"GoodBye demo workflow"
      shell: bash

       
       
